### ISSUE TITLE
Comment are not yet implemented right ?

### ISSUE THREAD

**Issue by AmibeSkyfy16** [xn32/json5k#1]
I tried to deserialize a json5 file with comment and then serialize it again, comment on the second file was not there anymore

I have an experimental project here https://github.com/AmibeSkyfy16/Json5ConfigLib

**Comment by xn32** [comment]
Thank you for your feedback.

Currently, the library ignores any kind of comment it encounters in an input stream. I'm afraid any other way of handling comments in the input stream would violate the following requirement from [section 9.1](https://spec.json5.org/1.0.0/#lexical-grammar) of the specification:

> [...] Simple white space and comments are discarded and do not appear in the stream of input elements for the syntactic grammar.

Enriching generated JSON5 output with comments from the internal data model should work, though. Could you please check if the following unit test meets your requirement?
```kotlin
val json5 = Json5 {
    prettyPrint = true
}

@Serializable
data class Point(
    @SerialComment("First comment") val x: Int,
    @SerialComment(" Second comment") val y: Int,

    @SerialComment(
        """
            Third comment (spanning
            multiple lines)
        """
    )
    val z: Int,
)

assertEquals(
    """
        {
            // First comment
            x: 400,
            // Second comment
            y: 500,
            // Third comment (spanning
            // multiple lines)
            z: 600
        }
    """.trimIndent(),
    json5.encodeToString(Point(400, 500, 600))
)
```

The name of the annotation is borrowed from [here](https://github.com/Kotlin/kotlinx.serialization/issues/1970). In addition, I have a slight preference to generate single-line comments instead of multi-line comments. With multi-line comments, we would have to protect the user from accidentally closing the comment, which would eventually result in the generation of an invalid JSON5 document.

Note that the leading space in the second comment is discarded. This is a consequence of a call to `trimIndent` made by the library. Various other libraries with this capability (including the [tomlkt](https://github.com/Peanuuutz/tomlkt/blob/212c95ba5d2b9169e50d1959e18c48652b472d1c/src/commonMain/kotlin/net/peanuuutz/tomlkt/internal/TomlFileEncoder.kt#L548) library you mentioned) seem to process the comment like this. Until [this issue](https://youtrack.jetbrains.com/issue/KT-22505) is resolved, this is probably the best way to handle it.

**Comment by AmibeSkyfy16** [comment]
thanks for the explanation. i tried the test, but it doesn't work. here is the error

expected: <{
    // First comment
    x: 400,
    // Second comment
    y: 500,
    // Third comment (spanning
    // multiple lines)
    z: 600
}> but was: <{
    x: 400,
    y: 500,
    z: 600
}>

**Comment by xn32** [comment]
What I actually wanted to say is that it should be possible to implement the feature, not that it is already available. Sorry for the confusion.

So the question is: Would you be happy with the feature as it is outlined in the unit test? Or is there anything else you need?

**Comment by AmibeSkyfy16** [comment]
It would be perfect as described here

**Comment by AmibeSkyfy16** [comment]
Maybe i have an idea about another enhancement, but not important for now.

idea: keep existing comment of previous deserialized object


![image](https://user-images.githubusercontent.com/85696108/191895684-ec044ad9-bccb-4788-8eb0-5bf1d0ea23ec.png)

**Comment by xn32** [comment]
The serialization of comments for class properties (like you asked for in your initial post) is now possible, please see [here](https://github.com/xn32/json5k/blob/50eafa10625c2b449a19c63e8c9f18d27e00e6ce/README.md#serialization-of-comments-for-class-properties) for a usage example. The feature is already in the `main` branch and will soon be in version 0.2.0 of the library. Please feel free to reopen the issue or file a new one if you run into problems.

Preserving contextual comments during a transformation from JSON5 to an object hierarchy and back is, unfortunately, considerably more difficult. I am particularly concerned that implementing this feature would cause the API of `json5k` to diverge from the APIs of officially supported [kotlinx.serialization formats](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md), most importantly JSON. Therefore, I will not be able to implement it in the near future. Nevertheless, I agree it would be a powerful feature and am happy to reconsider when the library is a bit more mature.

**Comment by AmibeSkyfy16** [comment]
Great, thank you very much for the work, I will test this soon
