### ISSUE TITLE
Request: Migrate library to Kotlin Multiplatform

### ISSUE THREAD

**Issue by aSemy** [xn32/json5k#1]
I'd like to be able to use json5k in a Kotlin Multiplatform project. Currently json5k only targets JVM, so this is not possible.

There's basically 3 main tasks to do this

1. update the Gradle config
2. replace JVM specific code with multiplatform equivalents
3. update the tests

The docs will also have to be updated.

#### Update Gradle config

Nothing too exciting here, but this should be the first step. 

Initially json5k can be updated to be a multiplatform project that only targets the JVM. Additional targets can be added once the following steps are done.

#### JVM specific code

json5k has a limited amount of dependencies on JVM classes

* `java.io.BufferedWriter`
* `java.io.ByteArrayInputStream`
* `java.io.ByteArrayOutputStream`
* `java.io.Flushable`
* `java.io.IOException`
* `java.io.InputStream`
* `java.io.OutputStream`
* `java.io.Writer`

I haven't looked in detail, but these can probably be replaced with the multiplatform library [Okio](https://square.github.io/okio/). If you don't want to introduce a dependency, then it's possible to create [expect/actual definitions](https://kotlinlang.org/docs/multiplatform-connect-to-apis.html) per platform (although that could be a lot of work!).

#### Update the tests

JUnit is not multiplatform, so should be replaced.

Kotest (my recommendation) or kotlin.test are both suitable JUnit replacements for testing multiplatform code.

**Comment by xn32** [comment]
Thank you for your suggestion!

I am actually quite confident that all `java.io` dependencies could be completely removed from the core of the library. Therefore, a dependency on Okio (or similar) might not even be necessary.

For the parsing process, an [`InputReader` interface](https://github.com/xn32/json5k/blob/2b59860bf3e287008f253f84f6eb071f537ffc05/src/main/kotlin/io/github/xn32/json5k/parsing/InputReader.kt#L5) to decouple business logic from the input provider is already in place. I think we can just modify the [`Json5.decodeFromString` function](https://github.com/xn32/json5k/blob/2b59860bf3e287008f253f84f6eb071f537ffc05/src/main/kotlin/io/github/xn32/json5k/Json5.kt#L73) to forward JSON5 input sequences directly to this interface. Then, the [`Json5.decodeFromStream` function](https://github.com/xn32/json5k/blob/2b59860bf3e287008f253f84f6eb071f537ffc05/src/main/kotlin/io/github/xn32/json5k/Json5.kt#L103) would be the only location where expect/actual definitions are necessary. Since it's just one location, the effort should be manageable.

An analogous interface for the generator is not yet available, but it would probably be even easier to define and use.

Please let me know what you think. If you agree, I will try to get it done in the next weeks.

**Comment by aSemy** [comment]
> I am actually quite confident that all `java.io` dependencies could be completely removed from the core of the library. Therefore, a dependency on Okio (or similar) might not even be necessary.

Ah great!

I also had a further look into the testing. I saw that json5k already uses kotlinx.test, and only uses `@Nested` from JUnit, so that should be easy to migrate.

> Please let me know what you think. If you agree, I will try to get it done in the next weeks.

Sounds good 👍 

If you like I can get started by making a PR to convert the Gradle config? No code changes, only the build config. I've already done something similar in https://github.com/Kantis/ks3, so I can copy and paste stuff across.

**Comment by xn32** [comment]
Absolutely, I am happy to accept a PR on this. Thank you for offering your support!

**Comment by xn32** [comment]
Thank you for your PRs! In the meantime, I have removed all `java.io` dependencies from the core of the library and added a second target for testing purposes:
```kotlin
kotlin {
    js(IR) {
        nodejs()
    }
}
```

It is available in the [multiplatform](https://github.com/xn32/json5k/tree/multiplatform) branch. With this version, `Json5.encodeToString` and `Json5.decodeFromString` should now work on JavaScript platforms as well.

Unfortunately, I had to add `expect`/`actual` definitions for writing out floating-point values during the serialization of an object hierarchy. Previously, the library just used `Double.toString()`, but this call seems to behave inconsistently across different targets. Therefore, a platform-independent version of the library core depends on:
- https://discuss.kotlinlang.org/t/decimal-format-in-a-multi-platform-build/5692
- https://youtrack.jetbrains.com/issue/KT-21644

Did you have a specific target platform in mind when you opened the issue?

**Comment by aSemy** [comment]
Nice work!

I want to use json5k on Windows, macOS, and Linux.

**Comment by xn32** [comment]
Just a quick update on this: Serializing floating-point values in a portable manner turned out to be more difficult than expected. In my opinion, the json5k output should be independent of the utilized backend. As described in [this issue](https://github.com/Kotlin/kotlinx.serialization/issues/2128), however, such an independence is currently not even implemented by the official JSON format.

For the time being, I therefore decided to merge the support for only the JVM backend into the main branch. In case you want to give the current snapshot version a try, you can find it [here](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/xn32).

**Comment by ubuntudroid** [comment]
Thanks for your effort, everyone! 🙏  Would you mind adding support for `iosArm64`, `iosSimulatorArm64` and `iosX64` targets to the snapshot? Or is this out of scope of this issue?

**Comment by xn32** [comment]
Sure, not a problem at all!

I activated a bunch of native targets (including the ones you are asking for) and added a CI job to publish snapshots automatically. Please find the latest artifacts [here](https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/xn32). I am still a bit hesitant to release a stable multiplatform version, though. Experience reports on how the current snapshot behaves on native target platforms are highly welcome.

**Comment by ubuntudroid** [comment]
Awesome, many thanks @xn32 ! 🙏  Will try it out in the next days and let you know how it went!

**Comment by ubuntudroid** [comment]
@xn32 just tested it out, and it's working great! 🤗

**Comment by xn32** [comment]
Thank you for your feedback. In the next days, I will switch to v1.5.0 of kotlinx.serialization and use this opportunity to publish a stable version of all the currently available targets.

**Comment by xn32** [comment]
v0.3.0 is now available on [Maven Central](https://central.sonatype.com/artifact/io.github.xn32/json5k/0.3.0). It is tested to the best of my ability, but please keep in mind that it is still an experimental library without an entirely stable API. If you run into problems, I would appreciate your feedback. Support for the JS target still depends on the availability of a portable `String.format` function.

Therefore, I am going to close this issue for now. Thank you for your contributions, everyone!
